= google-java-format-gradle-plugin
:release-version: 0.2
:default-google-java-format-version: 0.1-alpha
:snapshot-version: 0.3-SNAPSHOT


A https://github.com/gradle/gradle[Gradle] plugin that utilizes
https://github.com/google/google-java-format[google-java-format] to
format the Java source files in your Gradle project.

image:https://travis-ci.org/sherter/google-java-format-gradle-plugin.svg?branch=master["Build
Status",
link="https://travis-ci.org/sherter/google-java-format-gradle-plugin"]

== Quick Start
* Apply the plugin in your build script (follow https://plugins.gradle.org/plugin/com.github.sherter.google-java-format[these instructions]
for Gradle versions below `2.1`)
+
[source,groovy]
[subs="attributes"]
----
plugins {
  id 'com.github.sherter.google-java-format' version '{release-version}'
}
----
+

* Make sure you have defined a repository that contains `google-java-format`
+
[source,groovy]
----
repositories {
  jcenter()
}
----

* Execute the task `googleJavaFormat` to format all `*.java` files in the project
+
[source,shell]
----
$ ./gradlew goJF
----
+
* Execute the task `verifyGoogleJavaFormat` to verify that all `*.java` files are formatted properly
+
[source,shell]
----
$ ./gradlew verGJF
----

== Extended Usage
* The plugin adds the extension `googleJavaFormat` to your project. Adjust the variable `toolVersion` to use a specific version of `google-java-format`. You can even define `SNAPSHOT` versions, but make sure that you have added a repository to the project that contains this version (e.g. `mavenLocal()`). For plugin version `{release-version}` this value defaults to `{default-google-java-format-version}`. On every new release the default value will be updated to the latest version of `google-java-format`.
+
[source,groovy]
[subs="attributes"]
----
googleJavaFormat {
  toolVersion '0.1-SNAPSHOT'
}
----

* The predefined tasks `googleJavaFormat` and `verifyGoogleJavaFormat` by default process all `*.java` files found in the project or any subproject (except for files in a `buildDir`). If you want to exclude specific files from a predefined task you can use https://docs.gradle.org/2.0/javadoc/org/gradle/api/tasks/util/PatternFilterable.html[Ant-style exclude patterns].
+
[source,groovy]
[subs="attributes"]
----
tasks.googleJavaFormat {
  exclude '**/*Template.java'
  exclude 'src/test/template_*'
}
----

* Define your own format or verification tasks, if the predefined ones don't suite you needs. Both task types `GoogleJavaFormat` and `VerifyGoogleJavaFormat` are subtypes of `https://docs.gradle.org/2.0/javadoc/org/gradle/api/tasks/SourceTask.html[SourceTask]` and can be configured accordingly. The task type `VerifyGoogleJavaFormat` also implements the interface `https://docs.gradle.org/2.0/javadoc/org/gradle/api/tasks/VerificationTask.html[VerificationTask]`.
+
[source,groovy]
----
import com.github.sherter.googlejavaformatgradleplugin.GoogleJavaFormat
import com.github.sherter.googlejavaformatgradleplugin.VerifyGoogleJavaFormat

task format(type: GoogleJavaFormat) {
  source 'src/main'
  source 'src/test'
  include '**/*.java'
  exclude '**/*Template.java'
}

task verifyFormatting(type: VerifyGoogleJavaFormat) {
  source 'src/main'
  include '**/*.java'
  ignoreFailures true
}
----

== Snapshots
On every push to the master branch https://travis-ci.org/[Travis] runs
the tests and, if all tests pass, publishes the built artifact to
https://oss.sonatype.org/content/repositories/snapshots/[Sonatype's
`snapshots` repository]. Use the following build script snippet for
the current snapshot version:

[source,groovy]
[subs="attributes"]
----
buildscript {
  repositories {
    maven {
      url 'https://oss.sonatype.org/content/repositories/snapshots/'
    }
  }
  dependencies {
    classpath 'com.github.sherter.googlejavaformatgradleplugin:google-java-format-gradle-plugin:{snapshot-version}'
  }
}

apply plugin: 'com.github.sherter.google-java-format'
----


